# Pandas

## series

In [198]:
import pandas as pd
import numpy as np
#series创建
s = pd.Series([10,2,3,4,5])
print(s)
#自定义索引
# s = pd.Series([10,2,3,4,5],index=['a','b','c','d','e'])
# print(s)
#自定义name
s = pd.Series([10,2,3,4,5],index=['a','b','c','d','e'],name = '月份')
s['f']=6
s['g'] = 10
print(s)

0    10
1     2
2     3
3     4
4     5
dtype: int64
a    10
b     2
c     3
d     4
e     5
f     6
g    10
Name: 月份, dtype: int64

In [199]:
#通过字典来创建
# s= pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5})
# print(s)
s1 = pd.Series(s,index=['a','e'])
print(s1)

a    10
e     5
Name: 月份, dtype: int64

In [200]:
print(s)
print(s.index)
print(s.values)
print(s.shape)
print(s.ndim)
print(s.size)
print(s.dtype,s.name)
print(s.loc['b']) #显 式索引
print(s.iloc[3])  #隐式索引

a    10
b     2
c     3
d     4
e     5
f     6
g    10
Name: 月份, dtype: int64
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')
[10  2  3  4  5  6 10]
(7,)
1
7
int64 月份
2
4

In [201]:
print(s.iloc[3])
print(s.at['a'])
print(s.iat[0])

4
10
10

In [202]:
#访问数据
print(s['a'])
print(s['c'])

print(s[s<4])

print(s.head()) #打印前五行
print(s.head(3)) #前三行
print(s.tail())

10
3
b    2
c    3
Name: 月份, dtype: int64
a    10
b     2
c     3
d     4
e     5
Name: 月份, dtype: int64
a    10
b     2
c     3
Name: 月份, dtype: int64
c     3
d     4
e     5
f     6
g    10
Name: 月份, dtype: int64

In [203]:
#  常见函数
#
#

s = pd.Series([10,2,np.nan,None,3,4,5],index=['a','b','c','d','e','f','g'],name='data')
print(s)

print(s.head())
s.tail(3)

a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
f     4.0
g     5.0
Name: data, dtype: float64
a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
Name: data, dtype: float64

e    3.0
f    4.0
g    5.0
Name: data, dtype: float64

In [204]:
s.describe()

count     5.000000
mean      4.800000
std       3.114482
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max      10.000000
Name: data, dtype: float64

In [205]:
#获取元素个数,忽略缺失值
print(s.count())

5

In [206]:
s.keys() #有括号的是一种方法

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')

In [207]:
print(s.isna())

a    False
b    False
c     True
d     True
e    False
f    False
g    False
Name: data, dtype: bool

In [208]:
s.isin([4,5,6]) #用来检查元素是否在里面

a    False
b    False
c    False
d    False
e    False
f     True
g     True
Name: data, dtype: bool

In [209]:
print(s.describe())
print(s.mean())
print(s.std())
print(s.sum())
print(s.median())
s.sort_values()
print(s.quantile(0.25))
print(s.quantile(0.75))
print(s.quantile(0.8)) #4个间隔 * 0.8 = 3.2 跳过三个间隔,第四个间隔(10-5)*0.2=1  5+1=6

count     5.000000
mean      4.800000
std       3.114482
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max      10.000000
Name: data, dtype: float64
4.8
3.1144823004794877
24.0
4.0
3.0
5.0
6.000000000000001

In [210]:
s.sort_values()

b     2.0
e     3.0
f     4.0
g     5.0
a    10.0
c     NaN
d     NaN
Name: data, dtype: float64

In [211]:
s['h']=4
print(s)
print(s.mode())
print(s.value_counts())

a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
f     4.0
g     5.0
h     4.0
Name: data, dtype: float64
0    4.0
Name: data, dtype: float64
data
4.0     2
10.0    1
2.0     1
3.0     1
5.0     1
Name: count, dtype: int64

In [212]:
s.drop_duplicates() #去重

a    10.0
b     2.0
c     NaN
e     3.0
f     4.0
g     5.0
Name: data, dtype: float64

In [213]:
s.unique()

array([10.,  2., nan,  3.,  4.,  5.])

In [214]:
print(s.nunique()) #获取去重后的个数

5

In [215]:
s.sort_index() #按索引排序

a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
f     4.0
g     5.0
h     4.0
Name: data, dtype: float64

In [216]:
s.sort_values() #按值排序

b     2.0
e     3.0
f     4.0
h     4.0
g     5.0
a    10.0
c     NaN
d     NaN
Name: data, dtype: float64

## 案例分析

In [217]:
#生成10名学生数学成绩的series,50-100分,计算平均最低最高,找出高于平均的人数
np.random.seed(42)
scores = pd.Series(np.random.randint(50,101,10),index=['学生'+str(i) for i in range(1,11)])
print(scores)

学生1     88
学生2     78
学生3     64
学生4     92
学生5     57
学生6     70
学生7     88
学生8     68
学生9     72
学生10    60
dtype: int64

In [218]:
np.random.seed(42)
values = np.random.randint(50,101,10)
index = []
for i in range(1,11):
    index.append('学生'+str(i))
print(index)
print(values)

['学生1', '学生2', '学生3', '学生4', '学生5', '学生6', '学生7', '学生8', '学生9', '学生10']
[88 78 64 92 57 70 88 68 72 60]

In [219]:
print(scores.mean())
print(scores.min())
print(scores.max())
print(scores[scores>scores.mean()])
print(len(scores[scores>scores.mean()]))

73.7
57
92
学生1    88
学生2    78
学生4    92
学生7    88
dtype: int64
4

In [220]:
import pandas as pd
import numpy as np
np.random.seed(42)
values = np.random.randint(50,101,10)
indexes = []
for i in range(1,11):
    indexes.append('学生'+str(i))
scores = pd.Series(values,indexes)
print(scores)

print(scores.mean())
print(scores.min())
print(scores.max())
print(len(scores[scores>scores.mean()]))
print(scores[scores>scores.mean()].count())

学生1     88
学生2     78
学生3     64
学生4     92
学生5     57
学生6     70
学生7     88
学生8     68
学生9     72
学生10    60
dtype: int64
73.7
57
92
4
4

In [221]:
#给定一周温度,找出超过30°C的天数,计算平均温,从高到低排序,找出温度变化最大的两天
import pandas as pd
import numpy as np
temp = pd.Series([28,31,29,32,30,27,33],index=['周一','周二','周三','周四','周五','周六','周日'])
print(temp[temp>30].count())
print(temp.mean())
print(temp.sort_values(ascending=False))

t = abs(temp.diff())
print(t.sort_values(ascending = False).keys()[:2].tolist())
print(*(t.sort_values(ascending = False).keys()[:2].tolist()))

3
30.0
周日    33
周四    32
周二    31
周五    30
周三    29
周一    28
周六    27
dtype: int64
['周日', '周二']
周日 周二

In [222]:
#给定10个交易日股票收盘价,计算每日收益率,找出最低最高收益率的日期,计算波动率(收益率的标准差)
prices = pd.Series([102.3,103.5,105.1,104.8,106.2,107.0,106.5,108.1,109.3,110.2],index=pd.date_range('2023-01-01',periods=10))
prices.pct_change()  #percent (今天/昨天)-1
a = prices.pct_change()
print(a)
print(a.max())
print(a.idxmax())
print(a.std())

2023-01-01         NaN
2023-01-02    0.011730
2023-01-03    0.015459
2023-01-04   -0.002854
2023-01-05    0.013359
2023-01-06    0.007533
2023-01-07   -0.004673
2023-01-08    0.015023
2023-01-09    0.011101
2023-01-10    0.008234
Freq: D, dtype: float64
0.015458937198067568
2023-01-03 00:00:00
0.007373623845361105

In [223]:
 #12个月销售量,计算季度平均销售量,最高销售量月份,月环比增长率,找出连续增长超过2个月的月份
sales = pd.Series([120,135,145,160,155,170,180,175,190,200,210,220],index=pd.date_range('2022-01-01',periods=12,freq='MS'))
print(sales)
sales.resample('QS').mean() #重新采样
print("最大销售额",sales.max())
print("最大销售额月份",sales.idxmax())
print("月环比增长率",sales.pct_change())
a = sales.pct_change()
b = a>0
print(b[b.rolling(3).sum()==3].keys().tolist())

2022-01-01    120
2022-02-01    135
2022-03-01    145
2022-04-01    160
2022-05-01    155
2022-06-01    170
2022-07-01    180
2022-08-01    175
2022-09-01    190
2022-10-01    200
2022-11-01    210
2022-12-01    220
Freq: MS, dtype: int64
最大销售额 220
最大销售额月份 2022-12-01 00:00:00
月环比增长率 2022-01-01         NaN
2022-02-01    0.125000
2022-03-01    0.074074
2022-04-01    0.103448
2022-05-01   -0.031250
2022-06-01    0.096774
2022-07-01    0.058824
2022-08-01   -0.027778
2022-09-01    0.085714
2022-10-01    0.052632
2022-11-01    0.050000
2022-12-01    0.047619
Freq: MS, dtype: float64
[Timestamp('2022-04-01 00:00:00'), Timestamp('2022-11-01 00:00:00'), Timestamp('2022-12-01 00:00:00')]

In [224]:
#每小时销售额 计算每日总销售额,计算营业时间(8-10)和非营业时间销售额比例,找出销售额最高的三小时
import pandas as pd
import numpy as np
np.random.seed(42)
#print(pd.Series(np.random.randint(0,100,24)))
h = pd.Series(np.random.randint(0,100,24),index = pd.date_range('2026-01-01',periods=24,freq='h'))
print(h)
day_sales = h.resample('D').sum()
#hours_sales.between_time('8:00',"22:00")   #筛选一段时间内
b = h[(h.index.hour>=8)&(h.index.hour<=22)]
n_b = h.drop(b.index)
#print(business_hours_sales)
print("营业时间和非营业时间销售额比例",b.sum() / n_b.sum(  ))

2026-01-01 00:00:00    51
2026-01-01 01:00:00    92
2026-01-01 02:00:00    14
2026-01-01 03:00:00    71
2026-01-01 04:00:00    60
2026-01-01 05:00:00    20
2026-01-01 06:00:00    82
2026-01-01 07:00:00    86
2026-01-01 08:00:00    74
2026-01-01 09:00:00    74
2026-01-01 10:00:00    87
2026-01-01 11:00:00    99
2026-01-01 12:00:00    23
2026-01-01 13:00:00     2
2026-01-01 14:00:00    21
2026-01-01 15:00:00    52
2026-01-01 16:00:00     1
2026-01-01 17:00:00    87
2026-01-01 18:00:00    29
2026-01-01 19:00:00    37
2026-01-01 20:00:00     1
2026-01-01 21:00:00    63
2026-01-01 22:00:00    59
2026-01-01 23:00:00    20
Freq: h, dtype: int64
营业时间和非营业时间销售额比例 1.4294354838709677

## DataFrame

In [225]:
# 通过Series来创建
import pandas as pd
import numpy as np
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])
df = pd.DataFrame({"第一列":s1,"第二列":s2})

# 通过字典创建
df = pd.DataFrame(
    {
        "id":[1,1,2,3,4,5],
        "name":["tom","tom","jack","alice","bob","allen"],
        "age":[15,15,15,20,26,30],
        "score":[60.5,60.5,80,30.6,70,83.5]
    },index=[1,2,3,4,5,6],columns=["id","name","age","score"]
)
df

   id   name  age  score
1   1    tom   15   60.5
2   1    tom   15   60.5
3   2   jack   15   80.0
4   3  alice   20   30.6
5   4    bob   26   70.0
6   5  allen   30   83.5

In [226]:
print(df.index) #行索引
print(df.columns) #列标签
print(df.values) #值
print(df.ndim) #维度
print(df.dtypes) #每一列的数据类型
print(df.shape)
print(df.size)

Index([1, 2, 3, 4, 5, 6], dtype='int64')
Index(['id', 'name', 'age', 'score'], dtype='str')
[[1 'tom' 15 60.5]
 [1 'tom' 15 60.5]
 [2 'jack' 15 80.0]
 [3 'alice' 20 30.6]
 [4 'bob' 26 70.0]
 [5 'allen' 30 83.5]]
2
id         int64
name         str
age        int64
score    float64
dtype: object
(6, 4)
24

In [227]:
print(df.T)
print(df.T.index)
print(df.T.columns)

          1     2     3      4     5      6
id        1     1     2      3     4      5
name    tom   tom  jack  alice   bob  allen
age      15    15    15     20    26     30
score  60.5  60.5  80.0   30.6  70.0   83.5
Index(['id', 'name', 'age', 'score'], dtype='str')
Index([1, 2, 3, 4, 5, 6], dtype='int64')

In [228]:
print(df)
print(df.loc[4]) #获取某行数据
print(df.iloc[3])
print(df.loc[:,'name']) #获取某列
print(df.iloc[:,1])
print(df.at[3,'score']) #获取单个元素
print(df.iat[2,3])
print(df.loc[3,'score'])
print(df.iloc[2,3])

   id   name  age  score
1   1    tom   15   60.5
2   1    tom   15   60.5
3   2   jack   15   80.0
4   3  alice   20   30.6
5   4    bob   26   70.0
6   5  allen   30   83.5
id           3
name     alice
age         20
score     30.6
Name: 4, dtype: object
id           3
name     alice
age         20
score     30.6
Name: 4, dtype: object
1      tom
2      tom
3     jack
4    alice
5      bob
6    allen
Name: name, dtype: str
1      tom
2      tom
3     jack
4    alice
5      bob
6    allen
Name: name, dtype: str
80.0
80.0
80.0
80.0

In [229]:
#获取某列数据
print(df['name'])
print(df.name)
#查看部分数据
print(df.head(3))

1      tom
2      tom
3     jack
4    alice
5      bob
6    allen
Name: name, dtype: str
1      tom
2      tom
3     jack
4    alice
5      bob
6    allen
Name: name, dtype: str
   id  name  age  score
1   1   tom   15   60.5
2   1   tom   15   60.5
3   2  jack   15   80.0

In [230]:
#布尔索引来筛选数据
df[df.score>70]
df[(df.score>70)&(df.age<20)]

   id  name  age  score
3   2  jack   15   80.0

In [231]:
#随机抽样
df.sample(3)

   id   name  age  score
3   2   jack   15   80.0
6   5  allen   30   83.5
5   4    bob   26   70.0

In [232]:
print(df)
print(df.head(1))
print(df.tail(1))
print(df.isin(['jack',20]))
print(df.isna())
print(df.age.sum())
print(df.score.sum())
print(df.score.max())
print(df.score.mean())
print(df.score.median())
print(df.age.mode())
print(df.score.std())
print(df.score.var())
print(df.score.quantile(0.25))
print(df.describe())

   id   name  age  score
1   1    tom   15   60.5
2   1    tom   15   60.5
3   2   jack   15   80.0
4   3  alice   20   30.6
5   4    bob   26   70.0
6   5  allen   30   83.5
   id name  age  score
1   1  tom   15   60.5
   id   name  age  score
6   5  allen   30   83.5
      id   name    age  score
1  False  False  False  False
2  False  False  False  False
3  False   True  False  False
4  False  False   True  False
5  False  False  False  False
6  False  False  False  False
      id   name    age  score
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False
6  False  False  False  False
121
385.1
83.5
64.18333333333334
65.25
0    15
Name: age, dtype: int64
19.037375519400424
362.4216666666666
60.5
             id        age      score
count  6.000000   6.000000   6.000000
mean   2.666667  20.166667  64.183333
std    1.632993   6.493587  19.037376
min    1.000000  15.000000  30.600000
25%    1.250000  15.000000  60.500000
50%    2.500000  17.500000  65.250000
75%    3.750000  24.500000  77.500000
max    5.000000  30.000000  83.500000

In [235]:
print(df.duplicated())
print(df.drop_duplicates())

1    False
2     True
3    False
4    False
5    False
6    False
dtype: bool
   id   name  age  score
1   1    tom   15   60.5
3   2   jack   15   80.0
4   3  alice   20   30.6
5   4    bob   26   70.0
6   5  allen   30   83.5

In [236]:
df.sample(2)

   id   name  age  score
2   1    tom   15   60.5
6   5  allen   30   83.5

In [237]:
print(df.replace(15,99))

   id   name  age  score
1   1    tom   99   60.5
2   1    tom   99   60.5
3   2   jack   99   80.0
4   3  alice   20   30.6
5   4    bob   26   70.0
6   5  allen   30   83.5

In [240]:
print(df)
print(df.cumsum())  #累积和

   id   name  age  score
1   1    tom   15   60.5
2   1    tom   15   60.5
3   2   jack   15   80.0
4   3  alice   20   30.6
5   4    bob   26   70.0
6   5  allen   30   83.5
   id                     name  age  score
1   1                      tom   15   60.5
2   2                   tomtom   30  121.0
3   4               tomtomjack   45  201.0
4   7          tomtomjackalice   65  231.6
5  11       tomtomjackalicebob   91  301.6
6  16  tomtomjackaliceboballen  121  385.1

In [247]:
print(df.sort_index(ascending=False))
print(df.sort_values(by="name"))  #按首字母排序
print(df.sort_values(by="score"))  #按分数排序
print(df.sort_values(by=["score","age"],ascending=[False,True]))

   id   name  age  score
6   5  allen   30   83.5
5   4    bob   26   70.0
4   3  alice   20   30.6
3   2   jack   15   80.0
2   1    tom   15   60.5
1   1    tom   15   60.5
   id   name  age  score
4   3  alice   20   30.6
6   5  allen   30   83.5
5   4    bob   26   70.0
3   2   jack   15   80.0
1   1    tom   15   60.5
2   1    tom   15   60.5
   id   name  age  score
4   3  alice   20   30.6
1   1    tom   15   60.5
2   1    tom   15   60.5
5   4    bob   26   70.0
3   2   jack   15   80.0
6   5  allen   30   83.5
   id   name  age  score
6   5  allen   30   83.5
3   2   jack   15   80.0
5   4    bob   26   70.0
1   1    tom   15   60.5
2   1    tom   15   60.5
4   3  alice   20   30.6

In [253]:
df.nlargest(2,columns=['score','age'])

   id   name  age  score
6   5  allen   30   83.5
3   2   jack   15   80.0

In [256]:
#学生成绩分析
#计算每位学生总分和平均分,找出数学高于90英语高于85,按从高到低排并输出前三

import pandas as pd
import numpy as np
scores = pd.DataFrame({'姓名':['张三','李四','王五','赵六','钱七'],
                   '数学':[85,92,78,88,95],'英语':[90,88,85,92,80],'物理':[75,80,88,85,90]
                   })
print(scores)

   姓名  数学  英语  物理
0  张三  85  90  75
1  李四  92  88  80
2  王五  78  85  88
3  赵六  88  92  85
4  钱七  95  80  90

In [266]:
 #每个学生的总分
scores[['数学','英语','物理']] #提取学科列
scores['总分']=scores[['数学','英语','物理']].sum(axis=1) #转化为横向轴
#scores['平均分']=scores['总分']/3
scores['平均分']=scores[['数学','英语','物理']].mean(axis=1)
scores

   姓名  数学  英语  物理   总分        平均分
0  张三  85  90  75  250  83.333333
1  李四  92  88  80  260  86.666667
2  王五  78  85  88  251  83.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

In [267]:
scores[(scores['数学']>90)|(scores['英语']>85)]

   姓名  数学  英语  物理   总分        平均分
0  张三  85  90  75  250  83.333333
1  李四  92  88  80  260  86.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

In [270]:
scores.sort_values('总分',ascending=False).head(3)

   姓名  数学  英语  物理   总分        平均分
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667

In [271]:
scores.nlargest(3,columns=['总分'])

   姓名  数学  英语  物理   总分        平均分
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333
1  李四  92  88  80  260  86.666667